create extension if not exists "pgcrypto";

create table public.garages (id uuid primary key default gen_random_uuid(), owner_id uuid not null unique references auth.users(id) on delete cascade, name text not null, email text, phone text, created_at timestamptz not null default now());
create table public.customers (id uuid primary key default gen_random_uuid(), garage_id uuid not null references public.garages(id) on delete cascade, first_name text not null, last_name text not null, email text, phone text, last_visit_at date, total_spent numeric(12,2) not null default 0, risk_score integer not null default 0 check(risk_score between 0 and 100), risk_level text not null default 'low' check(risk_level in ('critical','high','medium','low')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index customers_garage_email_unique on public.customers(garage_id,email) where email is not null;
create table public.vehicles (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.customers(id) on delete cascade, make text, model text, registration text, mileage integer, created_at timestamptz not null default now());
create table public.visits (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.customers(id) on delete cascade, visited_at date not null, amount numeric(12,2) not null default 0, service_type text, created_at timestamptz not null default now());
create table public.campaigns (id uuid primary key default gen_random_uuid(), garage_id uuid not null references public.garages(id) on delete cascade, name text not null, status text not null default 'draft' check(status in ('draft','ready','sent')), created_at timestamptz not null default now());
create table public.messages (id uuid primary key default gen_random_uuid(), campaign_id uuid not null references public.campaigns(id) on delete cascade, customer_id uuid not null references public.customers(id) on delete cascade, channel text not null default 'email' check(channel in ('email','sms')), content text not null, status text not null default 'draft' check(status in ('draft','sent','failed')), sent_at timestamptz, created_at timestamptz not null default now());

create or replace function public.owns_garage(target_garage uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.garages where id=target_garage and owner_id=auth.uid())$$;
alter table public.garages enable row level security; alter table public.customers enable row level security; alter table public.vehicles enable row level security; alter table public.visits enable row level security; alter table public.campaigns enable row level security; alter table public.messages enable row level security;
create policy "own garage" on public.garages for all using (owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy "own customers" on public.customers for all using (public.owns_garage(garage_id)) with check(public.owns_garage(garage_id));
create policy "own vehicles" on public.vehicles for all using (exists(select 1 from public.customers c where c.id=customer_id and public.owns_garage(c.garage_id))) with check(exists(select 1 from public.customers c where c.id=customer_id and public.owns_garage(c.garage_id)));
create policy "own visits" on public.visits for all using (exists(select 1 from public.customers c where c.id=customer_id and public.owns_garage(c.garage_id))) with check(exists(select 1 from public.customers c where c.id=customer_id and public.owns_garage(c.garage_id)));
create policy "own campaigns" on public.campaigns for all using (public.owns_garage(garage_id)) with check(public.owns_garage(garage_id));
create policy "own messages" on public.messages for all using (exists(select 1 from public.campaigns ca join public.customers cu on cu.id=customer_id where ca.id=campaign_id and cu.garage_id=ca.garage_id and public.owns_garage(ca.garage_id))) with check(exists(select 1 from public.campaigns ca join public.customers cu on cu.id=customer_id where ca.id=campaign_id and cu.garage_id=ca.garage_id and public.owns_garage(ca.garage_id)));

create or replace function public.set_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now(); return new; end;$$;
create trigger customers_updated_at before update on public.customers for each row execute procedure public.set_updated_at();
create or replace function public.create_garage_for_user() returns trigger language plpgsql security definer set search_path=public as $$begin if new.raw_user_meta_data->>'garage_name' is not null then insert into public.garages(owner_id,name) values(new.id,new.raw_user_meta_data->>'garage_name'); end if; return new; end;$$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.create_garage_for_user();
